# Generated by Django 5.2.5 on 2025-08-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Dados brutos')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Usuário')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do split')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Dados brutos')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='payments.transaction', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Split',
                'verbose_name_plural': 'Splits',
            },
        ),
    ]
