# Generated by Django 5.2.5 on 2025-08-29 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=65, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Situacao do Split',
                'verbose_name_plural': 'Situacoes dos Splits',
            },
        ),
        migrations.AlterField(
            model_name='split',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do split'),
        ),
        migrations.AlterField(
            model_name='split',
            name='raw_data',
            field=models.JSONField(default=dict, verbose_name='dados brutos'),
        ),
        migrations.AlterField(
            model_name='split',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='payments.transaction', verbose_name='transacao'),
        ),
        migrations.AlterField(
            model_name='split',
            name='user',
            field=models.CharField(max_length=100, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de criacao'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_data',
            field=models.JSONField(default=dict, verbose_name='dados brutos'),
        ),
        migrations.AddField(
            model_name='split',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.statussplit', verbose_name='Status'),
        ),
    ]
