# Generated by Django 5.2.5 on 2025-08-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_statussplit_alter_split_amount_alter_split_raw_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.statussplit', verbose_name='Status'),
        ),
    ]
