# Generated by Django 5.2.5 on 2025-08-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_split_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
